import { PassiveNode } from './PassiveTreeTypes';

export const PASSIVE_TREE_NODES: Record<string, PassiveNode> = {
  root: {
    id: 'root',
    name: 'Gốc Thiên Phú',
    description: 'Nguồn cội tiềm năng của Lưu Đày Giả.',
    nodeType: 'start',
    branch: 'neutral',
    gridX: 0,
    gridY: 0,
    connections: ['str_1', 'dex_1', 'int_1', 'ring_aoe', 'ring_cdr'],
    modifiers: [],
  },

  // === VÒNG TRÒN TRUNG TÂM (UTILITY) ===
  ring_aoe: {
    id: 'ring_aoe',
    name: 'Khuếch Tán Diện Rộng',
    description: '+25 Bán kính vụ nổ (AoE Radius)',
    nodeType: 'small',
    branch: 'neutral',
    gridX: -45,
    gridY: 35,
    connections: ['root'],
    modifiers: [{ type: 'extra_pierce', value: 1 }],
  },
  ring_cdr: {
    id: 'ring_cdr',
    name: 'Hồi Chiêu Thần Tốc',
    description: '+15% Tốc độ ra đòn cho mọi kỹ năng',
    nodeType: 'small',
    branch: 'neutral',
    gridX: 45,
    gridY: 35,
    connections: ['root'],
    modifiers: [{ type: 'attack_speed_pct', value: 15 }],
  },

  // === NHÁNH ĐỎ: CHIẾN BINH (STRENGTH) ===
  str_1: {
    id: 'str_1',
    name: 'Thân Thể Bất Khuất',
    description: '+30 Máu Tối Đa',
    nodeType: 'small',
    branch: 'strength',
    gridX: -70,
    gridY: -50,
    connections: ['root', 'str_2', 'str_life_pct'],
    modifiers: [{ type: 'flat_life', value: 30 }],
  },
  str_life_pct: {
    id: 'str_life_pct',
    name: 'Khí Huyết Dồi Dào',
    description: '+45 Máu Tối Đa',
    nodeType: 'small',
    branch: 'strength',
    gridX: -110,
    gridY: -20,
    connections: ['str_1'],
    modifiers: [{ type: 'flat_life', value: 45 }],
  },
  str_2: {
    id: 'str_2',
    name: 'Tôi Luyện Thiết Giáp',
    description: '+40 Giáp Vật Lý',
    nodeType: 'small',
    branch: 'strength',
    gridX: -140,
    gridY: -80,
    connections: ['str_1', 'str_3', 'str_iron_will'],
    modifiers: [{ type: 'flat_armour', value: 40 }],
  },
  str_iron_will: {
    id: 'str_iron_will',
    name: 'Ý Chí Sắt Đá (Iron Will)',
    description: '+50 Giáp Vật Lý, +20 Máu Tối Đa',
    nodeType: 'notable',
    branch: 'strength',
    gridX: -180,
    gridY: -45,
    connections: ['str_2'],
    modifiers: [
      { type: 'flat_armour', value: 50 },
      { type: 'flat_life', value: 20 },
    ],
  },
  str_3: {
    id: 'str_3',
    name: 'Trảm Kích Hùng Lực',
    description: '+30% Sát Thương Vật Lý',
    nodeType: 'notable',
    branch: 'strength',
    gridX: -210,
    gridY: -110,
    connections: ['str_2', 'str_keystone', 'str_resolute'],
    modifiers: [{ type: 'inc_phys_damage', value: 30 }],
  },
  str_resolute: {
    id: 'str_resolute',
    name: 'Keystone: Resolute Technique',
    description: '+50% Sát Thương Vật Lý, Đòn Đánh Luôn Chuẩn Xác',
    nodeType: 'keystone',
    branch: 'strength',
    gridX: -270,
    gridY: -80,
    connections: ['str_3'],
    modifiers: [{ type: 'inc_phys_damage', value: 50 }],
  },
  str_keystone: {
    id: 'str_keystone',
    name: 'Keystone: Juggernaut',
    description: '+80 Máu Tối Đa, +80 Giáp Vật Lý',
    nodeType: 'keystone',
    branch: 'strength',
    gridX: -280,
    gridY: -140,
    connections: ['str_3'],
    modifiers: [
      { type: 'flat_life', value: 80 },
      { type: 'flat_armour', value: 80 },
    ],
  },

  // === NHÁNH XANH LÁ: XẠ THỦ (DEXTERITY) ===
  dex_1: {
    id: 'dex_1',
    name: 'Thần Tốc Hành Quân',
    description: '+20 Tốc Độ Di Chuyển',
    nodeType: 'small',
    branch: 'dexterity',
    gridX: 0,
    gridY: 70,
    connections: ['root', 'dex_2', 'dex_evasion_boost'],
    modifiers: [{ type: 'movement_speed', value: 20 }],
  },
  dex_evasion_boost: {
    id: 'dex_evasion_boost',
    name: 'Linh Hoạt Bộ Pháp',
    description: '+15 Tốc Độ Di Chuyển, +15 Né Đòn',
    nodeType: 'small',
    branch: 'dexterity',
    gridX: -50,
    gridY: 110,
    connections: ['dex_1'],
    modifiers: [
      { type: 'movement_speed', value: 15 },
      { type: 'flat_evasion', value: 15 },
    ],
  },
  dex_2: {
    id: 'dex_2',
    name: 'Vũ Điệu Cung Vũ',
    description: '+20% Tốc Độ Bắn Kỹ Năng',
    nodeType: 'small',
    branch: 'dexterity',
    gridX: 0,
    gridY: 130,
    connections: ['dex_1', 'dex_3', 'dex_point_blank'],
    modifiers: [{ type: 'attack_speed_pct', value: 20 }],
  },
  dex_point_blank: {
    id: 'dex_point_blank',
    name: 'Điểm Hỏa Cận Chiến (Point Blank)',
    description: '+1 Tia Đạn Bổ Sung, +10% Tốc Độ Bắn',
    nodeType: 'notable',
    branch: 'dexterity',
    gridX: 50,
    gridY: 165,
    connections: ['dex_2'],
    modifiers: [
      { type: 'extra_projectile', value: 1 },
      { type: 'attack_speed_pct', value: 10 },
    ],
  },
  dex_3: {
    id: 'dex_3',
    name: 'Hư Ứng Vô Ảnh',
    description: '+30 Tỷ Lệ Né Đòn (Evasion)',
    nodeType: 'notable',
    branch: 'dexterity',
    gridX: 0,
    gridY: 190,
    connections: ['dex_2', 'dex_keystone'],
    modifiers: [{ type: 'flat_evasion', value: 30 }],
  },
  dex_keystone: {
    id: 'dex_keystone',
    name: 'Keystone: Deadeye',
    description: '+2 Tia Đạn Bổ Sung, +2 Lần Xuyên Thấu',
    nodeType: 'keystone',
    branch: 'dexterity',
    gridX: 0,
    gridY: 245,
    connections: ['dex_3'],
    modifiers: [
      { type: 'extra_projectile', value: 2 },
      { type: 'extra_pierce', value: 2 },
    ],
  },

  // === NHÁNH XANH LAM: PHÁP SƯ (INTELLIGENCE) ===
  int_1: {
    id: 'int_1',
    name: 'Màn Chắn Tâm Linh',
    description: '+40 Khiên Năng Lượng (Energy Shield)',
    nodeType: 'small',
    branch: 'intelligence',
    gridX: 70,
    gridY: -50,
    connections: ['root', 'int_2', 'int_cast_speed'],
    modifiers: [{ type: 'flat_es', value: 40 }],
  },
  int_cast_speed: {
    id: 'int_cast_speed',
    name: 'Ngưng Tụ Ma Lực',
    description: '+15% Tốc Độ Thi Triển Pháp Thuật',
    nodeType: 'small',
    branch: 'intelligence',
    gridX: 110,
    gridY: -20,
    connections: ['int_1'],
    modifiers: [{ type: 'attack_speed_pct', value: 15 }],
  },
  int_2: {
    id: 'int_2',
    name: 'Hỏa Băng Hủy Diệt',
    description: '+30% Sát Thương Nguyên Tố',
    nodeType: 'small',
    branch: 'intelligence',
    gridX: 140,
    gridY: -80,
    connections: ['int_1', 'int_3', 'int_overload'],
    modifiers: [{ type: 'inc_fire_damage', value: 30 }],
  },
  int_overload: {
    id: 'int_overload',
    name: 'Quá Tải Nguyên Tố (Elemental Overload)',
    description: '+8% Tỷ Lệ Chí Mạng, +40 Khiên Năng Lượng',
    nodeType: 'notable',
    branch: 'intelligence',
    gridX: 180,
    gridY: -45,
    connections: ['int_2'],
    modifiers: [
      { type: 'crit_chance', value: 8 },
      { type: 'flat_es', value: 40 },
    ],
  },
  int_3: {
    id: 'int_3',
    name: 'Khai Mở Tiêu Điểm',
    description: '+10% Tỷ Lệ Chí Mạng, +0.3x Sát Thương Chí Mạng',
    nodeType: 'notable',
    branch: 'intelligence',
    gridX: 210,
    gridY: -110,
    connections: ['int_2', 'int_keystone'],
    modifiers: [
      { type: 'crit_chance', value: 10 },
      { type: 'crit_multiplier', value: 0.3 },
    ],
  },
  int_keystone: {
    id: 'int_keystone',
    name: 'Keystone: Archmage',
    description: '+80 Khiên Năng Lượng, +0.5x Sát Thương Chí Mạng',
    nodeType: 'keystone',
    branch: 'intelligence',
    gridX: 280,
    gridY: -140,
    connections: ['int_3'],
    modifiers: [
      { type: 'flat_es', value: 80 },
      { type: 'crit_multiplier', value: 0.5 },
    ],
  },
};
