import { PassiveNode } from './PassiveTreeTypes';

export const PASSIVE_TREE_NODES: Record<string, PassiveNode> = {
  root: {
    id: 'root',
    name: 'Gốc Thiên Phú',
    description: 'Nguồn cội tiềm năng của Lưu Đày Giả.',
    nodeType: 'start',
    branch: 'neutral',
    gridX: 0,
    gridY: 0,
    connections: ['str_1', 'dex_1', 'int_1', 'util_pickup', 'util_exp'],
    modifiers: [],
  },

  // === NHÁNH TIỆN ÍCH TRUNG TÂM ===
  util_pickup: {
    id: 'util_pickup',
    name: 'Từ Trường Thu Gom',
    description: '+80 Tầm Hút Đồ (Pickup Radius)',
    nodeType: 'notable',
    branch: 'neutral',
    gridX: -50,
    gridY: 35,
    connections: ['root'],
    modifiers: [{ type: 'pickup_radius', value: 80 }],
  },
  util_exp: {
    id: 'util_exp',
    name: 'Học Thức Uyên Bác',
    description: '+25% Kinh Nghiệm (EXP) Thu Nhận',
    nodeType: 'notable',
    branch: 'neutral',
    gridX: 50,
    gridY: 35,
    connections: ['root'],
    modifiers: [{ type: 'exp_bonus_pct', value: 25 }],
  },

  // === NHÁNH ĐỎ: CHIẾN BINH (STRENGTH) ===
  str_1: {
    id: 'str_1',
    name: 'Thân Thể Bất Khuất',
    description: '+35 Máu Tối Đa',
    nodeType: 'small',
    branch: 'strength',
    gridX: -70,
    gridY: -50,
    connections: ['root', 'str_2', 'str_life_pct'],
    modifiers: [{ type: 'flat_life', value: 35 }],
  },
  str_life_pct: {
    id: 'str_life_pct',
    name: 'Huyết Khí Tráng Kiện',
    description: '+50 Máu Tối Đa',
    nodeType: 'small',
    branch: 'strength',
    gridX: -115,
    gridY: -15,
    connections: ['str_1', 'str_bloodline'],
    modifiers: [{ type: 'flat_life', value: 50 }],
  },
  str_bloodline: {
    id: 'str_bloodline',
    name: 'Khát Máu Chiến Binh',
    description: '+60 Máu Tối Đa, +15% Sát Thương Vật Lý',
    nodeType: 'notable',
    branch: 'strength',
    gridX: -165,
    gridY: -15,
    connections: ['str_life_pct'],
    modifiers: [
      { type: 'flat_life', value: 60 },
      { type: 'inc_phys_damage', value: 15 },
    ],
  },
  str_2: {
    id: 'str_2',
    name: 'Tôi Luyện Thiết Giáp',
    description: '+45 Giáp Vật Lý',
    nodeType: 'small',
    branch: 'strength',
    gridX: -140,
    gridY: -75,
    connections: ['str_1', 'str_3', 'str_iron_will'],
    modifiers: [{ type: 'flat_armour', value: 45 }],
  },
  str_iron_will: {
    id: 'str_iron_will',
    name: 'Ý Chí Sắt Đá (Iron Will)',
    description: '+60 Giáp Vật Lý, +30 Máu Tối Đa',
    nodeType: 'notable',
    branch: 'strength',
    gridX: -190,
    gridY: -45,
    connections: ['str_2'],
    modifiers: [
      { type: 'flat_armour', value: 60 },
      { type: 'flat_life', value: 30 },
    ],
  },
  str_3: {
    id: 'str_3',
    name: 'Trảm Kích Hùng Lực',
    description: '+35% Sát Thương Vật Lý',
    nodeType: 'notable',
    branch: 'strength',
    gridX: -210,
    gridY: -105,
    connections: ['str_2', 'str_keystone', 'str_resolute'],
    modifiers: [{ type: 'inc_phys_damage', value: 35 }],
  },
  str_resolute: {
    id: 'str_resolute',
    name: 'Keystone: Resolute Technique',
    description: '+60% Sát Thương Vật Lý, Đòn Đánh Luôn Trúng Đích',
    nodeType: 'keystone',
    branch: 'strength',
    gridX: -270,
    gridY: -75,
    connections: ['str_3'],
    modifiers: [{ type: 'inc_phys_damage', value: 60 }],
  },
  str_keystone: {
    id: 'str_keystone',
    name: 'Keystone: Juggernaut',
    description: '+100 Máu Tối Đa, +100 Giáp Vật Lý',
    nodeType: 'keystone',
    branch: 'strength',
    gridX: -280,
    gridY: -135,
    connections: ['str_3'],
    modifiers: [
      { type: 'flat_life', value: 100 },
      { type: 'flat_armour', value: 100 },
    ],
  },

  // === NHÁNH XANH LÁ: XẠ THỦ (DEXTERITY) ===
  dex_1: {
    id: 'dex_1',
    name: 'Thần Tốc Hành Quân',
    description: '+25 Tốc Độ Di Chuyển',
    nodeType: 'small',
    branch: 'dexterity',
    gridX: 0,
    gridY: 70,
    connections: ['root', 'dex_2', 'dex_magnet'],
    modifiers: [{ type: 'movement_speed', value: 25 }],
  },
  dex_magnet: {
    id: 'dex_magnet',
    name: 'Gió Cuốn Thu Vật',
    description: '+60 Tầm Hút Đồ, +15 Tốc Độ Di Chuyển',
    nodeType: 'small',
    branch: 'dexterity',
    gridX: -55,
    gridY: 105,
    connections: ['dex_1'],
    modifiers: [
      { type: 'pickup_radius', value: 60 },
      { type: 'movement_speed', value: 15 },
    ],
  },
  dex_2: {
    id: 'dex_2',
    name: 'Vũ Điệu Cung Vũ',
    description: '+25% Tốc Độ Ra Đòn Kỹ Năng',
    nodeType: 'small',
    branch: 'dexterity',
    gridX: 0,
    gridY: 130,
    connections: ['dex_1', 'dex_3', 'dex_point_blank'],
    modifiers: [{ type: 'attack_speed_pct', value: 25 }],
  },
  dex_point_blank: {
    id: 'dex_point_blank',
    name: 'Điểm Hỏa (Point Blank)',
    description: '+1 Tia Đạn Bổ Sung, +15% Tốc Độ Bắn',
    nodeType: 'notable',
    branch: 'dexterity',
    gridX: 55,
    gridY: 165,
    connections: ['dex_2'],
    modifiers: [
      { type: 'extra_projectile', value: 1 },
      { type: 'attack_speed_pct', value: 15 },
    ],
  },
  dex_3: {
    id: 'dex_3',
    name: 'Hư Ứng Vô Ảnh',
    description: '+35 Tỷ Lệ Né Đòn (Evasion)',
    nodeType: 'notable',
    branch: 'dexterity',
    gridX: 0,
    gridY: 190,
    connections: ['dex_2', 'dex_keystone', 'dex_acro'],
    modifiers: [{ type: 'flat_evasion', value: 35 }],
  },
  dex_acro: {
    id: 'dex_acro',
    name: 'Keystone: Acrobatics',
    description: '+50 Tỷ Lệ Né Đòn Cực Hạn, +20 Tốc Chạy',
    nodeType: 'keystone',
    branch: 'dexterity',
    gridX: -65,
    gridY: 235,
    connections: ['dex_3'],
    modifiers: [
      { type: 'flat_evasion', value: 50 },
      { type: 'movement_speed', value: 20 },
    ],
  },
  dex_keystone: {
    id: 'dex_keystone',
    name: 'Keystone: Deadeye',
    description: '+2 Tia Đạn Bổ Sung, +2 Lần Xuyên Thấu',
    nodeType: 'keystone',
    branch: 'dexterity',
    gridX: 0,
    gridY: 245,
    connections: ['dex_3'],
    modifiers: [
      { type: 'extra_projectile', value: 2 },
      { type: 'extra_pierce', value: 2 },
    ],
  },

  // === NHÁNH XANH LAM: PHÁP SƯ (INTELLIGENCE) ===
  int_1: {
    id: 'int_1',
    name: 'Màn Chắn Tâm Linh',
    description: '+45 Khiên Năng Lượng (Energy Shield)',
    nodeType: 'small',
    branch: 'intelligence',
    gridX: 70,
    gridY: -50,
    connections: ['root', 'int_2', 'int_cast_speed'],
    modifiers: [{ type: 'flat_es', value: 45 }],
  },
  int_cast_speed: {
    id: 'int_cast_speed',
    name: 'Ngưng Tụ Ma Pháp',
    description: '+20% Tốc Độ Xuất Chiêu Pháp Thuật',
    nodeType: 'small',
    branch: 'intelligence',
    gridX: 115,
    gridY: -15,
    connections: ['int_1', 'int_ci'],
    modifiers: [{ type: 'attack_speed_pct', value: 20 }],
  },
  int_ci: {
    id: 'int_ci',
    name: 'Keystone: Chaos Inoculation',
    description: '+90 Khiên Năng Lượng Tối Đa',
    nodeType: 'keystone',
    branch: 'intelligence',
    gridX: 165,
    gridY: -15,
    connections: ['int_cast_speed'],
    modifiers: [{ type: 'flat_es', value: 90 }],
  },
  int_2: {
    id: 'int_2',
    name: 'Hỏa Băng Hủy Diệt',
    description: '+35% Sát Thương Nguyên Tố',
    nodeType: 'small',
    branch: 'intelligence',
    gridX: 140,
    gridY: -75,
    connections: ['int_1', 'int_3', 'int_overload'],
    modifiers: [{ type: 'inc_fire_damage', value: 35 }],
  },
  int_overload: {
    id: 'int_overload',
    name: 'Quá Tải Nguyên Tố (Elemental Overload)',
    description: '+10% Tỷ Lệ Chí Mạng, +45 Khiên Năng Lượng',
    nodeType: 'notable',
    branch: 'intelligence',
    gridX: 190,
    gridY: -45,
    connections: ['int_2'],
    modifiers: [
      { type: 'crit_chance', value: 10 },
      { type: 'flat_es', value: 45 },
    ],
  },
  int_3: {
    id: 'int_3',
    name: 'Khai Mở Tiêu Điểm',
    description: '+12% Tỷ Lệ Chí Mạng, +0.35x Sát Thương Chí Mạng',
    nodeType: 'notable',
    branch: 'intelligence',
    gridX: 210,
    gridY: -105,
    connections: ['int_2', 'int_keystone'],
    modifiers: [
      { type: 'crit_chance', value: 12 },
      { type: 'crit_multiplier', value: 0.35 },
    ],
  },
  int_keystone: {
    id: 'int_keystone',
    name: 'Keystone: Archmage',
    description: '+90 Khiên Năng Lượng, +0.6x Sát Thương Chí Mạng',
    nodeType: 'keystone',
    branch: 'intelligence',
    gridX: 280,
    gridY: -135,
    connections: ['int_3'],
    modifiers: [
      { type: 'flat_es', value: 90 },
      { type: 'crit_multiplier', value: 0.6 },
    ],
  },
};
