import { PassiveNode } from './PassiveTreeTypes';

export const PASSIVE_TREE_NODES: Record<string, PassiveNode> = {
  root: {
    id: 'root',
    name: 'Khởi Điểm Lưu Đày',
    description: 'Nguồn cội sức mạnh của kẻ sống sót.',
    nodeType: 'start',
    branch: 'neutral',
    gridX: 0,
    gridY: -10,
    connections: ['str_1', 'dex_1', 'int_1'],
    modifiers: [],
  },

  // === NHÁNH ĐỎ: SỨC MẠNH ===
  str_1: {
    id: 'str_1',
    name: 'Thân Thể Bất Khuất',
    description: '+30 Máu Tối Đa',
    nodeType: 'small',
    branch: 'strength',
    gridX: -70,
    gridY: -60,
    connections: ['root', 'str_2'],
    modifiers: [{ type: 'flat_life', value: 30 }],
  },
  str_2: {
    id: 'str_2',
    name: 'Tôi Luyện Thiết Giáp',
    description: '+40 Giáp Vật Lý',
    nodeType: 'small',
    branch: 'strength',
    gridX: -140,
    gridY: -100,
    connections: ['str_1', 'str_3'],
    modifiers: [{ type: 'flat_armour', value: 40 }],
  },
  str_3: {
    id: 'str_3',
    name: 'Trảm Kích Hùng Lực',
    description: '+25% Sát Thương Vật Lý',
    nodeType: 'notable',
    branch: 'strength',
    gridX: -210,
    gridY: -130,
    connections: ['str_2', 'str_keystone'],
    modifiers: [{ type: 'inc_phys_damage', value: 25 }],
  },
  str_keystone: {
    id: 'str_keystone',
    name: 'Keystone: Juggernaut',
    description: '+70 Máu Tối Đa, +60 Giáp Vật Lý',
    nodeType: 'keystone',
    branch: 'strength',
    gridX: -280,
    gridY: -150,
    connections: ['str_3'],
    modifiers: [
      { type: 'flat_life', value: 70 },
      { type: 'flat_armour', value: 60 },
    ],
  },

  // === NHÁNH XANH LÁ: KHÉO LÉO (Đã thu gọn để không bị chạm đáy) ===
  dex_1: {
    id: 'dex_1',
    name: 'Thần Tốc Hành Quân',
    description: '+20 Tốc Độ Di Chuyển',
    nodeType: 'small',
    branch: 'dexterity',
    gridX: 0,
    gridY: 45,
    connections: ['root', 'dex_2'],
    modifiers: [{ type: 'movement_speed', value: 20 }],
  },
  dex_2: {
    id: 'dex_2',
    name: 'Vũ Điệu Cung Vũ',
    description: '+20% Tốc Độ Bắn Kỹ Năng',
    nodeType: 'small',
    branch: 'dexterity',
    gridX: 0,
    gridY: 95,
    connections: ['dex_1', 'dex_3'],
    modifiers: [{ type: 'attack_speed_pct', value: 20 }],
  },
  dex_3: {
    id: 'dex_3',
    name: 'Hư Ứng Vô Ảnh',
    description: '+25 Tỷ Lệ Né Đòn (Evasion)',
    nodeType: 'notable',
    branch: 'dexterity',
    gridX: 0,
    gridY: 145,
    connections: ['dex_2', 'dex_keystone'],
    modifiers: [{ type: 'flat_evasion', value: 25 }],
  },
  dex_keystone: {
    id: 'dex_keystone',
    name: 'Keystone: Deadeye',
    description: '+1 Tia Đạn Bổ Sung, +2 Lần Xuyên Thấu',
    nodeType: 'keystone',
    branch: 'dexterity',
    gridX: 0,
    gridY: 195,
    connections: ['dex_3'],
    modifiers: [
      { type: 'extra_projectile', value: 1 },
      { type: 'extra_pierce', value: 2 },
    ],
  },

  // === NHÁNH XANH LAM: TRÍ TUỆ ===
  int_1: {
    id: 'int_1',
    name: 'Màn Chắn Tâm Linh',
    description: '+35 Khiên Năng Lượng (Energy Shield)',
    nodeType: 'small',
    branch: 'intelligence',
    gridX: 70,
    gridY: -60,
    connections: ['root', 'int_2'],
    modifiers: [{ type: 'flat_es', value: 35 }],
  },
  int_2: {
    id: 'int_2',
    name: 'Hỏa Cầu Hủy Diệt',
    description: '+25% Sát Thương Lửa',
    nodeType: 'small',
    branch: 'intelligence',
    gridX: 140,
    gridY: -100,
    connections: ['int_1', 'int_3'],
    modifiers: [{ type: 'inc_fire_damage', value: 25 }],
  },
  int_3: {
    id: 'int_3',
    name: 'Khai Mở Tiêu Điểm',
    description: '+8% Tỷ Lệ Chí Mạng',
    nodeType: 'notable',
    branch: 'intelligence',
    gridX: 210,
    gridY: -130,
    connections: ['int_2', 'int_keystone'],
    modifiers: [{ type: 'crit_chance', value: 8 }],
  },
  int_keystone: {
    id: 'int_keystone',
    name: 'Keystone: Archmage',
    description: '+60 Khiên Năng Lượng, +30% Sát Thương Chí Mạng',
    nodeType: 'keystone',
    branch: 'intelligence',
    gridX: 280,
    gridY: -150,
    connections: ['int_3'],
    modifiers: [
      { type: 'flat_es', value: 60 },
      { type: 'crit_multiplier', value: 0.3 },
    ],
  },
};
