import { ActiveGem, SkillContext } from './GemTypes';

export const FireballSkill: ActiveGem = {
  id: 'fireball',
  name: 'Fireball',
  color: 'blue',
  getInitialContext: (): SkillContext => ({
    id: 'fireball',
    name: 'Fireball',
    damageType: 'fire',
    baseMinDamage: 25,
    baseMaxDamage: 40,
    addedMinDamage: 0,
    addedMaxDamage: 0,
    attackSpeedMultiplier: 1.0,
    baseCooldown: 700,
    projectileCount: 1,
    projectileSpeed: 380,
    pierceCount: 0,
    aoeRadius: 45,
    critChance: 6,
    critMultiplier: 1.5,
    increasedDamagePercent: 0,
    moreDamageMultipliers: [],
  }),
};

export const SplitArrowSkill: ActiveGem = {
  id: 'split_arrow',
  name: 'Split Arrow',
  color: 'green',
  getInitialContext: (): SkillContext => ({
    id: 'split_arrow',
    name: 'Split Arrow',
    damageType: 'physical',
    baseMinDamage: 18,
    baseMaxDamage: 32,
    addedMinDamage: 0,
    addedMaxDamage: 0,
    attackSpeedMultiplier: 1.2,
    baseCooldown: 500,
    projectileCount: 3,
    projectileSpeed: 520,
    pierceCount: 0,
    aoeRadius: 0,
    critChance: 5,
    critMultiplier: 1.5,
    increasedDamagePercent: 0,
    moreDamageMultipliers: [],
  }),
};

export const GroundSlamSkill: ActiveGem = {
  id: 'ground_slam',
  name: 'Ground Slam',
  color: 'red',
  getInitialContext: (): SkillContext => ({
    id: 'ground_slam',
    name: 'Ground Slam',
    damageType: 'physical',
    baseMinDamage: 40,
    baseMaxDamage: 75,
    addedMinDamage: 0,
    addedMaxDamage: 0,
    attackSpeedMultiplier: 0.85,
    baseCooldown: 900,
    projectileCount: 1,
    projectileSpeed: 220,
    pierceCount: 99,
    aoeRadius: 70,
    critChance: 5,
    critMultiplier: 1.5,
    increasedDamagePercent: 0,
    moreDamageMultipliers: [],
  }),
};
