import { ActiveGem, SkillContext } from './GemTypes';

export const FireballSkill: ActiveGem = {
  id: 'fireball',
  name: 'Fireball',
  color: 'blue',
  iconColor: 0xef4444,
  getInitialContext: (level = 1): SkillContext => ({
    id: 'fireball',
    name: 'Fireball',
    level,
    damageType: 'fire',
    baseMinDamage: Math.round(28 * (1 + (level - 1) * 0.3)),
    baseMaxDamage: Math.round(45 * (1 + (level - 1) * 0.3)),
    addedMinDamage: 0,
    addedMaxDamage: 0,
    attackSpeedMultiplier: 1.0 + (level - 1) * 0.05,
    baseCooldown: 700,
    projectileCount: 1 + Math.floor((level - 1) / 3),
    projectileSpeed: 380,
    pierceCount: 0,
    aoeRadius: 45 + (level - 1) * 6,
    critChance: 6,
    critMultiplier: 1.5,
    increasedDamagePercent: 0,
    moreDamageMultipliers: [],
  }),
};

export const SplitArrowSkill: ActiveGem = {
  id: 'split_arrow',
  name: 'Split Arrow',
  color: 'green',
  iconColor: 0x22c55e,
  getInitialContext: (level = 1): SkillContext => ({
    id: 'split_arrow',
    name: 'Split Arrow',
    level,
    damageType: 'physical',
    baseMinDamage: Math.round(18 * (1 + (level - 1) * 0.25)),
    baseMaxDamage: Math.round(32 * (1 + (level - 1) * 0.25)),
    addedMinDamage: 0,
    addedMaxDamage: 0,
    attackSpeedMultiplier: 1.25,
    baseCooldown: 500,
    projectileCount: 3 + (level - 1),
    projectileSpeed: 520,
    pierceCount: Math.floor((level - 1) / 2),
    aoeRadius: 0,
    critChance: 5,
    critMultiplier: 1.5,
    increasedDamagePercent: 0,
    moreDamageMultipliers: [],
  }),
};

export const GroundSlamSkill: ActiveGem = {
  id: 'ground_slam',
  name: 'Ground Slam',
  color: 'red',
  iconColor: 0xd97706,
  getInitialContext: (level = 1): SkillContext => ({
    id: 'ground_slam',
    name: 'Ground Slam',
    level,
    damageType: 'physical',
    baseMinDamage: Math.round(45 * (1 + (level - 1) * 0.35)),
    baseMaxDamage: Math.round(80 * (1 + (level - 1) * 0.35)),
    addedMinDamage: 0,
    addedMaxDamage: 0,
    attackSpeedMultiplier: 0.85,
    baseCooldown: Math.max(500, 900 - (level - 1) * 60),
    projectileCount: 1,
    projectileSpeed: 240,
    pierceCount: 99,
    aoeRadius: 75 + (level - 1) * 10,
    critChance: 5,
    critMultiplier: 1.5,
    increasedDamagePercent: 0,
    moreDamageMultipliers: [],
  }),
};

export const FrostboltSkill: ActiveGem = {
  id: 'frostbolt',
  name: 'Frostbolt',
  color: 'blue',
  iconColor: 0x06b6d4,
  getInitialContext: (level = 1): SkillContext => ({
    id: 'frostbolt',
    name: 'Frostbolt',
    level,
    damageType: 'cold',
    baseMinDamage: Math.round(32 * (1 + (level - 1) * 0.28)),
    baseMaxDamage: Math.round(52 * (1 + (level - 1) * 0.28)),
    addedMinDamage: 0,
    addedMaxDamage: 0,
    attackSpeedMultiplier: 0.95,
    baseCooldown: 650,
    projectileCount: 1 + Math.floor((level - 1) / 2),
    projectileSpeed: 320,
    pierceCount: 99,
    aoeRadius: 30,
    critChance: 7,
    critMultiplier: 1.5,
    increasedDamagePercent: 0,
    moreDamageMultipliers: [],
  }),
};

export const SparkSkill: ActiveGem = {
  id: 'spark',
  name: 'Spark',
  color: 'blue',
  iconColor: 0xfacc15,
  getInitialContext: (level = 1): SkillContext => ({
    id: 'spark',
    name: 'Spark',
    level,
    damageType: 'lightning',
    baseMinDamage: Math.round(12 * (1 + (level - 1) * 0.3)),
    baseMaxDamage: Math.round(48 * (1 + (level - 1) * 0.3)),
    addedMinDamage: 0,
    addedMaxDamage: 0,
    attackSpeedMultiplier: 1.4,
    baseCooldown: 550,
    projectileCount: 4 + (level - 1) * 2,
    projectileSpeed: 450,
    pierceCount: 1 + Math.floor((level - 1) / 2),
    aoeRadius: 0,
    critChance: 8,
    critMultiplier: 1.6,
    increasedDamagePercent: 0,
    moreDamageMultipliers: [],
  }),
};

export const BladeVortexSkill: ActiveGem = {
  id: 'blade_vortex',
  name: 'Blade Vortex',
  color: 'green',
  iconColor: 0xa855f7,
  getInitialContext: (level = 1): SkillContext => ({
    id: 'blade_vortex',
    name: 'Blade Vortex',
    level,
    damageType: 'physical',
    baseMinDamage: Math.round(15 * (1 + (level - 1) * 0.25)),
    baseMaxDamage: Math.round(25 * (1 + (level - 1) * 0.25)),
    addedMinDamage: 0,
    addedMaxDamage: 0,
    attackSpeedMultiplier: 2.0,
    baseCooldown: 300,
    projectileCount: 3 + (level - 1),
    projectileSpeed: 180,
    pierceCount: 99,
    aoeRadius: 40 + (level - 1) * 5,
    critChance: 6,
    critMultiplier: 1.5,
    increasedDamagePercent: 0,
    moreDamageMultipliers: [],
  }),
};

// KỸ NĂNG MỚI: ARC (Tia Sét Xích Điện)
export const ArcSkill: ActiveGem = {
  id: 'arc',
  name: 'Arc',
  color: 'blue',
  iconColor: 0x38bdf8,
  getInitialContext: (level = 1): SkillContext => ({
    id: 'arc',
    name: 'Arc',
    level,
    damageType: 'lightning',
    baseMinDamage: Math.round(20 * (1 + (level - 1) * 0.32)),
    baseMaxDamage: Math.round(65 * (1 + (level - 1) * 0.32)),
    addedMinDamage: 0,
    addedMaxDamage: 0,
    attackSpeedMultiplier: 1.2,
    baseCooldown: 480,
    projectileCount: 2 + (level - 1),
    projectileSpeed: 600,
    pierceCount: 2,
    aoeRadius: 0,
    critChance: 9,
    critMultiplier: 1.65,
    increasedDamagePercent: 0,
    moreDamageMultipliers: [],
  }),
};

// KỸ NĂNG MỚI: MOLTEN STRIKE (Hỏa Nham Đao)
export const MoltenStrikeSkill: ActiveGem = {
  id: 'molten_strike',
  name: 'Molten Strike',
  color: 'red',
  iconColor: 0xf97316,
  getInitialContext: (level = 1): SkillContext => ({
    id: 'molten_strike',
    name: 'Molten Strike',
    level,
    damageType: 'fire',
    baseMinDamage: Math.round(35 * (1 + (level - 1) * 0.3)),
    baseMaxDamage: Math.round(60 * (1 + (level - 1) * 0.3)),
    addedMinDamage: 0,
    addedMaxDamage: 0,
    attackSpeedMultiplier: 1.1,
    baseCooldown: 620,
    projectileCount: 3 + (level - 1),
    projectileSpeed: 300,
    pierceCount: 0,
    aoeRadius: 55,
    critChance: 6,
    critMultiplier: 1.5,
    increasedDamagePercent: 0,
    moreDamageMultipliers: [],
  }),
};

// KỸ NĂNG MỚI: TOXIC SPORE (Bào Tử Độc Tố)
export const ToxicSporeSkill: ActiveGem = {
  id: 'toxic_spore',
  name: 'Toxic Spore',
  color: 'green',
  iconColor: 0x10b981,
  getInitialContext: (level = 1): SkillContext => ({
    id: 'toxic_spore',
    name: 'Toxic Spore',
    level,
    damageType: 'chaos',
    baseMinDamage: Math.round(22 * (1 + (level - 1) * 0.28)),
    baseMaxDamage: Math.round(42 * (1 + (level - 1) * 0.28)),
    addedMinDamage: 0,
    addedMaxDamage: 0,
    attackSpeedMultiplier: 1.3,
    baseCooldown: 450,
    projectileCount: 3 + (level - 1),
    projectileSpeed: 400,
    pierceCount: 1,
    aoeRadius: 40,
    critChance: 5,
    critMultiplier: 1.4,
    increasedDamagePercent: 0,
    moreDamageMultipliers: [],
  }),
};

export const ALL_ACTIVE_SKILLS: Record<string, ActiveGem> = {
  fireball: FireballSkill,
  split_arrow: SplitArrowSkill,
  ground_slam: GroundSlamSkill,
  frostbolt: FrostboltSkill,
  spark: SparkSkill,
  blade_vortex: BladeVortexSkill,
  arc: ArcSkill,
  molten_strike: MoltenStrikeSkill,
  toxic_spore: ToxicSporeSkill,
};
